package-lock.json
package.json
src/components/App/ExpressRecorder.tsx
src/components/App/style.scss
src/components/Recorder/Recorder.tsx

Added option to record from <canvas> instead of webcam

Canvas express recorder

---

package.json
src/components/App/ExpressRecorder.tsx
src/components/App/style.scss
src/components/Recording-timer/RecordingTimer.tsx
src/components/Recording-timer/style.scss

KMS-21384-added-focus-to-button-after-red-button-was-clicked

---

src/components/Playback/Playback.tsx
src/components/Recorder/Recorder.tsx

KMS 21626 - cancel autoplay

---

src/components/Settings/Settings.tsx
src/components/Settings/style.scss

KMS-21629 - use SR only elements

---

src/components/Settings/style.scss

KMS-21627 - set link focus color

---

src/components/Settings/Settings-devices.tsx
src/components/Settings/Settings.tsx
src/components/Toggle-button/ToggleButton.tsx

Kms 21625 ensure the setting menu items provide proper textual name, role, and state information

---

src/components/App/ExpressRecorder.tsx

KMS-21385 - move text to recording button

---

src/components/Recorder/Recorder.tsx

SUP-26386 add WebM codecs in the syntax FF supports

---

src/components/App/ExpressRecorder.tsx

SUP-27813 modify constraints according to client available devices

---

src/components/App/ExpressRecorder.tsx

KMS-25515 - Express Capture - do not auto start when "record again" is pressed

---

package.json
src/components/App/ExpressRecorder.tsx
src/components/Recorder/Recorder.tsx

Kms 25277 express recorder   after completing a recording the record duration time is not correctly displayed

---

src/components/Settings/Settings-devices.tsx
src/components/Settings/Settings.tsx

KMS-21625 - interact with menu items by pressing space bar

---

package-lock.json
src/components/App/ExpressRecorder.tsx
src/components/Playback/Playback.tsx
src/components/Playback/player.css
src/components/Playback/style.scss
src/components/Settings/Settings.tsx
webpack.config.js

Ilms 212 make share screen ability configurable

---

src/components/App/ExpressRecorder.tsx
src/components/Recorder/Recorder.tsx
src/components/Settings/Settings.tsx

Ilms 288 camera is turning off when choosing audio devica

---

src/components/App/ExpressRecorder.tsx
src/components/AudioIndicator/AudioIndicator.tsx
src/components/Playback/Playback.tsx
src/components/Playback/player.css
src/components/Recorder/Recorder.tsx
src/components/Settings/Settings.tsx

Ilms 279 behavior of screen sharing with camera or audio off and on

---

src/components/App/ExpressRecorder.tsx
src/components/Recorder/Recorder.tsx

Ilms 290 after disabling screen share is still on and camera is off

---

src/components/App/ExpressRecorder.tsx

ILMS-297 - dispatch event when recording screen and audio only

---

src/components/Recorder/Recorder.tsx

Ilms 304 fix error message

---

src/components/App/ExpressRecorder.tsx
src/components/Recorder/Recorder.tsx

ILMS-303 - fix dowload of 2 files when camera off

---

src/components/App/ExpressRecorder.tsx
src/components/Error-screen/ErrorScreen.tsx
src/components/Error-screen/style.scss
src/components/Recorder/Recorder.tsx

Ilms 302 add reset button to error message

---

src/components/App/ExpressRecorder.tsx
src/components/Recorder/Recorder.tsx
src/components/Settings/Settings.tsx

Ilms 121 bugs fixing

---

src/components/App/ExpressRecorder.tsx
src/components/Playback/Playback.tsx
src/components/Recorder/Recorder.tsx

ILMS-311 - use fixed blob to set in player instead the accumulted ones

---

src/components/App/ExpressRecorder.tsx

ILMS-335 - add option to enable screen audio

---

src/components/App/ExpressRecorder.tsx

ILMS-334 - fix condition - recording can have audio only

---

src/components/Settings/Settings.tsx

ILMS-288 - fix conditions - don't sent device if resource is off

---

src/components/App/ExpressRecorder.tsx
src/components/Settings/Settings.tsx
src/components/Settings/style.scss
src/components/Toggle-button/style.scss
src/public/assets/style.scss
src/public/assets/variables.scss

Ilms 306 design fixes

---

src/components/App/ExpressRecorder.tsx
src/components/App/style.scss
src/components/Recorder/Recorder.tsx
src/components/Recorder/style.scss
src/components/Uploader/UploadManager.tsx

Ilms 280 extend recording time limit

---

src/components/App/ExpressRecorder.tsx
src/components/Recorder/Recorder.tsx

ILMS-361 - remove redundent prop. dont show stream if not active

---

src/components/Settings/Settings.tsx

ILMS-359 - close resource settings after changing settings

---

src/components/Playback/Playback.tsx

KMS-26811 adding default value so dualscreen plugin wont fail

---

src/components/Settings/Settings.tsx
src/components/Settings/style.scss

ILMS-363 - disable start button if all 3 devices are off

---

src/components/App/ExpressRecorder.tsx
src/components/Recording-timer/RecordingTimer.tsx

Sup 34877 express capture bug while using jaws

---

src/components/App/ExpressRecorder.tsx

KMS-27873 - set full HD to screen also

---

README.md

add comment about required privilege in KS

---

src/components/App/ExpressRecorder.tsx
src/components/Playback/Playback.tsx
src/components/Recorder/Recorder.tsx

Kms 27628 replace parent and child

---

src/components/App/style.scss
src/components/Settings/style.scss

With: https://github.com/kaltura/mediaspace/pull/14881

ADA-1316 - update styles for zoom 400 on right resolution

---

src/components/Settings/style.scss

ADA-1461 - refactor the styling to fit on all browsers

---

src/components/Settings/Settings-devices.tsx
src/components/Settings/style.scss
src/components/Toggle-button/ToggleButton.tsx
src/components/Toggle-button/style.scss

ADA-411 inside video recording toggle on off option is not accessible with keyboard

---

src/components/Settings/Settings.tsx

ADA-1518 - Add alt text to control buttons icons

---

README.md
src/components/App/ExpressRecorder.tsx
src/components/Settings/Settings-devices.tsx
src/components/Settings/Settings.tsx
src/components/Toggle-button/ToggleButton.tsx
src/services/analytics/AnalyticsSender.ts
src/services/analytics/ButtonClickAnalyticsEventType.ts

Ilms 537 express capture   send product analytics

---

.github/workflows/upload-assests-to-s3.yaml

- **onboard s3 upload express**
- **e2e**
- **final**

upload to s3

---

src/components/App/style.scss
src/components/Countdown-timer/style.scss
src/components/Recording-timer/style.scss
src/components/Settings/Settings-devices.tsx
src/components/Settings/style.scss
src/components/Toggle-button/style.scss

ADA-1809 recorder plugin update zoom

---

src/components/Playback/Playback.tsx

fix(KMS-30782): remove fake entry ID

---

src/components/App/ExpressRecorder.tsx

SUP-38605 assist micro error on screen share in express capture

---

src/components/App/ExpressRecorder.tsx
src/components/App/style.scss

Problem: height auto was only applied for max-width 1024 before https://kaltura.atlassian.net/browse/SUP-47054 this fix
Solution: add height auto for max-width 1024 and when screen share is not on

SUP-47774 - add height auto only for max-width 1024px
